spring.application.name=journalapp
spring.data.mongodb.uri=mongodb+srv://sushant:Hande123@cluster0.ejketmg.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=journaldb
#spring.data.mongodb.auto-index-creation=true
#spring.data.mongodb.username=admin
#spring.data.mongodb.password=adminpassword