spring:
  data:
    mongodb:
      uri: mongodb+srv://sushant:Hande123@cluster0.ejketmg.mongodb.net/?appName=Cluster0
      database: journaldb
      auto-index-creation: true

server:
  port: 8080
#  servlet:
#    context-path: /journal